"""London Heathrow Airport (LHR) destinations — April 2026."""

DESTINATIONS = {
    "LHR": {
        "name": "London Heathrow",
        "routes": {
            # UK & Ireland
            "ABZ": "Aberdeen",
            "BHD": "Belfast City",
            "DND": "Dundee",
            "DUB": "Dublin",
            "EDI": "Edinburgh",
            "GCI": "Guernsey",
            "GIB": "Gibraltar",
            "GLA": "Glasgow",
            "INV": "Inverness",
            "IOM": "Isle of Man",
            "JER": "Jersey",
            "KOI": "Kirkwall",
            "LDY": "Derry",
            "LSI": "Sumburgh",
            "MAN": "Manchester",
            "NCL": "Newcastle",
            "NOC": "Knock",
            "ORK": "Cork",
            "SNN": "Shannon",
            # Spain (Mainland)
            "AGP": "Malaga",
            "BCN": "Barcelona",
            "BIO": "Bilbao",
            "LCG": "A Coruna",
            "MAD": "Madrid",
            "SCQ": "Santiago de Compostela",
            "SVQ": "Seville",
            "VLC": "Valencia",
            # Balearic Islands
            "IBZ": "Ibiza",
            "PMI": "Palma de Majorca",
            # Italy
            "BDS": "Brindisi",
            "BLQ": "Bologna",
            "FCO": "Rome Fiumicino",
            "FLR": "Florence",
            "LIN": "Milan Linate",
            "MXP": "Milan Malpensa",
            "NAP": "Naples",
            "OLB": "Olbia",
            "PEG": "Perugia",
            "PMO": "Palermo",
            "PSA": "Pisa",
            "RMI": "Rimini",
            "VCE": "Venice Marco Polo",
            # France
            "CDG": "Paris Charles de Gaulle",
            "FSC": "Figari (Corsica)",
            "LYS": "Lyon",
            "MRS": "Marseille",
            "NCE": "Nice",
            "ORY": "Paris Orly",
            "TLS": "Toulouse",
            # Germany
            "BER": "Berlin",
            "DUS": "Dusseldorf",
            "FRA": "Frankfurt",
            "HAJ": "Hanover",
            "HAM": "Hamburg",
            "MUC": "Munich",
            "NUE": "Nuremberg",
            "STR": "Stuttgart",
            # Greece
            "ATH": "Athens",
            "CFU": "Corfu",
            "CHQ": "Chania",
            "EFL": "Kefalonia",
            "HER": "Heraklion (Crete)",
            "JMK": "Mykonos",
            "JTR": "Santorini",
            "PVK": "Preveza",
            "RHO": "Rhodes",
            "SKG": "Thessaloniki",
            "ZTH": "Zakynthos (Zante)",
            # Portugal & Azores
            "FAO": "Faro",
            "LIS": "Lisbon",
            "PDL": "Ponta Delgada (Azores)",
            # Turkey
            "DLM": "Dalaman",
            "IST": "Istanbul",
            # Poland
            "KRK": "Krakow",
            "WAW": "Warsaw",
            # Romania
            "OTP": "Bucharest",
            # Austria & Switzerland
            "BSL": "Basel",
            "GVA": "Geneva",
            "INN": "Innsbruck",
            "SZG": "Salzburg",
            "VIE": "Vienna",
            "ZRH": "Zurich",
            # Eastern Europe & Balkans
            "BEG": "Belgrade",
            "BUD": "Budapest",
            "DBV": "Dubrovnik",
            "LJU": "Ljubljana",
            "PRG": "Prague",
            "SOF": "Sofia",
            "SPU": "Split",
            "TIA": "Tirana",
            "TIV": "Tivat",
            "ZAG": "Zagreb",
            # Scandinavia & Nordics
            "ARN": "Stockholm",
            "BLL": "Billund",
            "CPH": "Copenhagen",
            "GOT": "Gothenburg",
            "HEL": "Helsinki",
            "KEF": "Reykjavik",
            "OSL": "Oslo",
            "TOS": "Tromso",
            # Benelux & Luxembourg
            "AMS": "Amsterdam",
            "BRU": "Brussels",
            "LUX": "Luxembourg",
            # Cyprus
            "LCA": "Larnaca",
            "PFO": "Paphos",
            # Caucasus & Central Asia
            "ALA": "Almaty",
            "GYD": "Baku",
            "TAS": "Tashkent",
            "TBS": "Tbilisi",
            # North Africa
            "ALG": "Algiers",
            "CAI": "Cairo",
            "CMN": "Casablanca",
            "LXR": "Luxor",
            "RAK": "Marrakech",
            "TUN": "Tunis",
            # Sub-Saharan Africa
            "ABV": "Abuja",
            "ACC": "Accra",
            "ADD": "Addis Ababa",
            "CPT": "Cape Town",
            "JNB": "Johannesburg",
            "KGL": "Kigali",
            "LOS": "Lagos",
            "NBO": "Nairobi",
            # Middle East
            "AMM": "Amman",
            "AUH": "Abu Dhabi",
            "BAH": "Bahrain",
            "BEY": "Beirut",
            "DMM": "Dammam",
            "DOH": "Doha",
            "DWC": "Dubai Al Maktoum",
            "DXB": "Dubai",
            "JED": "Jeddah",
            "KWI": "Kuwait City",
            "MCT": "Muscat",
            "RUH": "Riyadh",
            "TLV": "Tel Aviv",
            # South Asia
            "BLR": "Bengaluru",
            "BOM": "Mumbai",
            "CMB": "Colombo",
            "DAC": "Dhaka",
            "DEL": "New Delhi",
            "HYD": "Hyderabad",
            "ISB": "Islamabad",
            "LHE": "Lahore",
            "MAA": "Chennai",
            "MLE": "Male (Maldives)",
            "ZYL": "Sylhet",
            # Southeast Asia
            "BKK": "Bangkok",
            "BWN": "Bandar Seri Begawan",
            "HAN": "Hanoi",
            "HKT": "Phuket",
            "KUL": "Kuala Lumpur",
            "SGN": "Ho Chi Minh City",
            "SIN": "Singapore",
            # East Asia
            "CAN": "Guangzhou",
            "CKG": "Chongqing",
            "CSX": "Changsha",
            "HAK": "Haikou",
            "HKG": "Hong Kong",
            "HND": "Tokyo Haneda",
            "ICN": "Seoul Incheon",
            "PEK": "Beijing Capital",
            "PKX": "Beijing Daxing",
            "PVG": "Shanghai",
            "SZX": "Shenzhen",
            "TAO": "Qingdao",
            "TFU": "Chengdu",
            "TPE": "Taipei",
            "TSN": "Tianjin",
            "WUH": "Wuhan",
            "XIY": "Xi'an",
            # Oceania
            "MEL": "Melbourne",
            "PER": "Perth",
            "SYD": "Sydney",
            # North America (USA)
            "ATL": "Atlanta",
            "AUS": "Austin",
            "BNA": "Nashville",
            "BOS": "Boston",
            "BWI": "Baltimore",
            "CLT": "Charlotte",
            "CVG": "Cincinnati",
            "DEN": "Denver",
            "DFW": "Dallas/Fort Worth",
            "DTW": "Detroit",
            "EWR": "Newark",
            "IAD": "Washington Dulles",
            "IAH": "Houston",
            "JFK": "New York JFK",
            "LAS": "Las Vegas",
            "LAX": "Los Angeles",
            "MCO": "Orlando",
            "MIA": "Miami",
            "MSP": "Minneapolis",
            "MSY": "New Orleans",
            "ORD": "Chicago O'Hare",
            "PDX": "Portland",
            "PHL": "Philadelphia",
            "PHX": "Phoenix",
            "PIT": "Pittsburgh",
            "RDU": "Raleigh-Durham",
            "SAN": "San Diego",
            "SEA": "Seattle",
            "SFO": "San Francisco",
            "SLC": "Salt Lake City",
            "STL": "St Louis",
            "TPA": "Tampa",
            # North America (Canada)
            "YHZ": "Halifax",
            "YOW": "Ottawa",
            "YUL": "Montreal",
            "YVR": "Vancouver",
            "YYC": "Calgary",
            "YYZ": "Toronto",
            # Caribbean & Central America
            "ANU": "Antigua",
            "BDA": "Bermuda",
            "BGI": "Barbados",
            "CUN": "Cancun",
            "GCM": "Grand Cayman",
            "GND": "Grenada",
            "MBJ": "Montego Bay",
            "MEX": "Mexico City",
            "NAS": "Nassau",
            "PLS": "Providenciales",
            "SJO": "San Jose (Costa Rica)",
            "SVD": "Kingstown (St Vincent)",
            # South America
            "BOG": "Bogota",
            "EZE": "Buenos Aires",
            "GIG": "Rio de Janeiro",
            "GRU": "Sao Paulo",
            "LIM": "Lima",
            "SCL": "Santiago",
            # Malta
            "MLA": "Malta",
        },
    },
}


def get_destinations(airport: str) -> dict:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("routes", {})


def get_airport_name(airport: str) -> str:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("name", airport)
